# Generated by Django 5.2.12 on 2026-03-19 00:38

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID compartilhado com Neo4j', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('senioridade', models.CharField(choices=[('junior', 'Júnior'), ('pleno', 'Pleno'), ('senior', 'Sênior')], default='junior', max_length=10)),
                ('anos_experiencia', models.PositiveIntegerField(default=0, help_text='Anos totais de experiência profissional', validators=[django.core.validators.MaxValueValidator(50)])),
                ('disponivel', models.BooleanField(default=True, help_text='Disponível para início imediato')),
                ('cv_s3_key', models.CharField(blank=True, help_text='Key do arquivo no S3 (ex: cvs/uuid/arquivo.pdf)', max_length=500)),
                ('status_cv', models.CharField(choices=[('pendente', 'Pendente'), ('recebido', 'Recebido'), ('processando', 'Lendo PDF'), ('extraindo', 'Extraindo habilidades'), ('concluido', 'Concluído'), ('erro', 'Erro no processamento')], default='pendente', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidato', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Candidato',
                'verbose_name_plural': 'Candidatos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField(blank=True)),
                ('area', models.CharField(help_text='Ex: Dados, Backend, Frontend, DevOps', max_length=100)),
                ('senioridade_desejada', models.CharField(choices=[('junior', 'Júnior'), ('pleno', 'Pleno'), ('senior', 'Sênior')], default='pleno', max_length=10)),
                ('skills_obrigatorias', models.JSONField(default=list, help_text='[{"nome": "Python", "nivel_minimo": 3}]')),
                ('skills_desejaveis', models.JSONField(default=list, help_text='[{"nome": "Docker", "nivel_minimo": 1}]')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('aberta', 'Aberta'), ('pausada', 'Pausada'), ('fechada', 'Fechada')], default='rascunho', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vagas_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vaga',
                'verbose_name_plural': 'Vagas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditoriaMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('snapshot_skills', models.JSONField(help_text='Snapshot completo das skills no momento do cálculo')),
                ('versao_algoritmo', models.CharField(default='1.0.0', help_text='Versão do algoritmo de matching usado', max_length=20)),
                ('detalhes_calculo', models.JSONField(default=dict, help_text='Breakdown: camada1_score, camada2_score, camada3_score')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='core.candidato')),
                ('vaga', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auditorias', to='core.vaga')),
            ],
            options={
                'verbose_name': 'Auditoria de Match',
                'verbose_name_plural': 'Auditorias de Match',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vaga', 'score'], name='core_audito_vaga_id_d37d2a_idx'), models.Index(fields=['candidato', 'created_at'], name='core_audito_candida_5abf83_idx')],
            },
        ),
    ]
