# Generated by Django 5.2.12 on 2026-03-21 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='etapa_processo',
            field=models.CharField(choices=[('triagem', 'Triagem'), ('entrevista_rh', 'Entrevista RH'), ('teste_tecnico', 'Teste Técnico'), ('entrevista_tecnica', 'Entrevista Técnica'), ('proposta', 'Proposta'), ('contratado', 'Contratado'), ('rejeitado', 'Rejeitado'), ('desistiu', 'Desistiu')], default='triagem', help_text='Etapa atual no processo seletivo', max_length=20),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('candidato', 'Candidato'), ('rh', 'Recrutador (RH)'), ('admin', 'Administrador')], default='candidato', max_length=10)),
                ('receber_notificacoes', models.BooleanField(default=True, help_text='Receber notificações por email')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil',
                'verbose_name_plural': 'Perfis',
            },
        ),
        migrations.CreateModel(
            name='HistoricoAcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_acao', models.CharField(choices=[('candidato_criado', 'Candidato criado'), ('candidato_editado', 'Candidato editado'), ('candidato_deletado', 'Candidato deletado'), ('cv_upload', 'CV enviado'), ('cv_visualizado', 'CV visualizado'), ('etapa_alterada', 'Etapa alterada'), ('vaga_criada', 'Vaga criada'), ('vaga_editada', 'Vaga editada'), ('vaga_deletada', 'Vaga deletada'), ('vaga_status', 'Status da vaga alterado'), ('matching', 'Matching executado'), ('login', 'Login'), ('logout', 'Logout')], max_length=30)),
                ('detalhes', models.JSONField(blank=True, default=dict, help_text='Detalhes da ação em JSON')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico', to='core.candidato')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico_acoes', to=settings.AUTH_USER_MODEL)),
                ('vaga', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historico', to='core.vaga')),
            ],
            options={
                'verbose_name': 'Histórico de Ação',
                'verbose_name_plural': 'Histórico de Ações',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['usuario', 'created_at'], name='core_histor_usuario_0fab2c_idx'), models.Index(fields=['tipo_acao', 'created_at'], name='core_histor_tipo_ac_02041f_idx'), models.Index(fields=['candidato', 'created_at'], name='core_histor_candida_9a29c7_idx')],
            },
        ),
    ]
