# Generated by Django 5.2.12 on 2026-03-22 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_comentario_favorito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Nome da tag (ex: 'Talento Top', 'Urgente')", max_length=50)),
                ('cor', models.CharField(choices=[('primary', 'Azul'), ('success', 'Verde'), ('danger', 'Vermelho'), ('warning', 'Amarelo'), ('purple', 'Roxo'), ('pink', 'Rosa'), ('orange', 'Laranja'), ('secondary', 'Cinza'), ('info', 'Ciano'), ('dark', 'Escuro')], default='primary', help_text='Cor para exibição visual', max_length=20)),
                ('descricao', models.TextField(blank=True, help_text='Descrição opcional do que significa essa tag')),
                ('global_tag', models.BooleanField(default=True, help_text='Tag visível para toda equipe RH')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags_criadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['nome'],
                'unique_together': {('nome', 'criado_por')},
            },
        ),
        migrations.CreateModel(
            name='CandidatoTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('aplicado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags_aplicadas', to=settings.AUTH_USER_MODEL)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidato_tags', to='core.candidato')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidato_tags', to='core.tag')),
            ],
            options={
                'verbose_name': 'Tag do Candidato',
                'verbose_name_plural': 'Tags dos Candidatos',
                'ordering': ['-created_at'],
                'unique_together': {('candidato', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='candidato',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='candidatos', through='core.CandidatoTag', to='core.tag'),
        ),
    ]
