# Generated by Django 5.2.12 on 2026-03-25 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tags_system'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiltroSalvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text="Nome descritivo (ex: 'Python Seniors Disponíveis')", max_length=100)),
                ('parametros', models.JSONField(default=dict, help_text='Parâmetros GET salvos do filtro')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('vezes_usado', models.PositiveIntegerField(default=0, help_text='Contador de uso para analytics')),
                ('usuario', models.ForeignKey(help_text='Usuário que criou o filtro', on_delete=django.db.models.deletion.CASCADE, related_name='filtros_salvos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Filtro Salvo',
                'verbose_name_plural': 'Filtros Salvos',
                'ordering': ['-atualizado_em'],
                'indexes': [models.Index(fields=['usuario', '-atualizado_em'], name='core_filtro_usuario_3a6fab_idx')],
                'unique_together': {('usuario', 'nome')},
            },
        ),
    ]
