# Generated by Django 5.2.12 on 2026-03-29 19:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_filtros_salvos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField(help_text='Texto da pergunta técnica gerada pela IA')),
                ('difficulty_level', models.CharField(choices=[('easy', 'Fácil'), ('medium', 'Médio'), ('hard', 'Difícil')], default='medium', help_text='Nível de dificuldade da pergunta', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp de criação da pergunta')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp de última atualização')),
                ('is_active', models.BooleanField(default=True, help_text='Ativa ou inativa (soft-delete para versioning)')),
                ('candidato', models.ForeignKey(help_text='Candidato para o qual a pergunta foi gerada', on_delete=django.db.models.deletion.CASCADE, related_name='interview_questions', to='core.candidato')),
                ('created_by', models.ForeignKey(blank=True, help_text='RH ou sistema que disparou a geração', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview_questions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Interview Question',
                'verbose_name_plural': 'Interview Questions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['candidato_id', 'is_active'], name='core_interv_candida_4de0a6_idx'), models.Index(fields=['created_by_id'], name='core_interv_created_414772_idx'), models.Index(fields=['is_active'], name='core_interv_is_acti_be55c1_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('candidato', 'is_active'), name='unique_active_questions_per_candidate')],
            },
        ),
    ]
