# Generated by Django 5.2.12 on 2026-04-02 23:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_interview_question_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='UUID do tenant — usado como prefixo no Neo4j', primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
                ('plano', models.CharField(choices=[('trial', 'Trial (14 dias)'), ('starter', 'Starter'), ('pro', 'Pro')], default='trial', max_length=20)),
                ('trial_expira_em', models.DateTimeField(blank=True, help_text='Preenchido automaticamente no onboarding (now + 14 dias)', null=True)),
                ('stripe_customer_id', models.CharField(blank=True, help_text='ID do customer no Stripe para reconciliação de webhooks', max_length=100)),
                ('max_candidatos', models.PositiveIntegerField(default=50, help_text='Limite de candidatos ativos. Trial=50, Starter=500, Pro=ilimitado')),
                ('max_vagas', models.PositiveIntegerField(default=5, help_text='Limite de vagas abertas simultâneas.')),
                ('ativo', models.BooleanField(default=True, help_text='False bloqueia acesso sem deletar dados (inadimplência, suspensão)')),
                ('dominio', models.CharField(blank=True, help_text='Subdomínio ou domínio customizado usado pelo TenantMiddleware', max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Organização',
                'verbose_name_plural': 'Organizações',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='candidato',
            name='lgpd_exclusao_data',
            field=models.DateTimeField(blank=True, help_text='Data da solicitação de exclusão', null=True),
        ),
        migrations.AddField(
            model_name='candidato',
            name='lgpd_exclusao_motivo',
            field=models.TextField(blank=True, help_text='Motivo da solicitação de exclusão'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='lgpd_exclusao_solicitada',
            field=models.BooleanField(default=False, help_text='Candidato solicitou exclusão de dados (LGPD Art. 18)'),
        ),
        migrations.AlterField(
            model_name='candidato',
            name='email',
            field=models.EmailField(help_text='Único por organização (tenant), não globalmente', max_length=254),
        ),
        migrations.AlterField(
            model_name='historicoacao',
            name='tipo_acao',
            field=models.CharField(choices=[('candidato_criado', 'Candidato criado'), ('candidato_editado', 'Candidato editado'), ('candidato_deletado', 'Candidato deletado'), ('cv_upload', 'CV enviado'), ('cv_visualizado', 'CV visualizado'), ('etapa_alterada', 'Etapa alterada'), ('vaga_criada', 'Vaga criada'), ('vaga_editada', 'Vaga editada'), ('vaga_deletada', 'Vaga deletada'), ('vaga_status', 'Status da vaga alterado'), ('matching', 'Matching executado'), ('login', 'Login'), ('logout', 'Logout'), ('lgpd_solicitacao', 'Solicitação LGPD'), ('lgpd_export', 'Exportação de dados LGPD')], max_length=30),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='auditoriamatch',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Tenant — mantido mesmo se vaga/candidato forem deletados (LGPD)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='core.organization'),
        ),
        migrations.AddField(
            model_name='candidato',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Tenant ao qual este candidato pertence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='core.organization'),
        ),
        migrations.AddField(
            model_name='filtrosalvo',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Filtros salvos são escopados por tenant', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filtros_salvos', to='core.organization'),
        ),
        migrations.AddField(
            model_name='historicoacao',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historico_acoes', to='core.organization'),
        ),
        migrations.AddField(
            model_name='profile',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Organização à qual este usuário pertence. Null = superadmin global', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='membros', to='core.organization'),
        ),
        migrations.AddField(
            model_name='tag',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Tags são escopadas por tenant', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.organization'),
        ),
        migrations.AddField(
            model_name='vaga',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='Tenant ao qual esta vaga pertence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='core.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('nome', 'organization')},
        ),
        migrations.AddConstraint(
            model_name='candidato',
            constraint=models.UniqueConstraint(fields=('organization', 'email'), name='candidato_organization_email_uniq'),
        ),
    ]
