# Generated by hand on 2026-06-17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_performance_indexes'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='interviewquestion',
            name='unique_active_questions_per_candidate',
        ),
    ]
